version: '3'

services:
  php-laravel:
    build: ./services/php-laravel
    tty: true
    volumes:
      - ../:/workspace:cached
  postgres:
    build: ./services/postgres
    environment:
      POSTGRES_PASSWORD: laravel
      POSTGRES_USER: laravel
      POSTGRES_DB: railroad_local
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    restart: always
    shm_size: 128mb
    volumes:
      - ./services/postgres/initdb.d:/docker-entrypoint-initdb.d
